variable "ENGINE" {}
variable "ENGINE_VERSION" {}
variable "NODE_TYPE" {}
variable "NODE_COUNT" {}
variable "FAMILY" {}
variable "ENV" {}
variable "COMPONENT" {}
variable "VPC_ID" {}
variable "VPC_CIDR" {}
variable "SUBNET_IDS" {}