variable "EC_ENGINE" {}
variable "EC_ENGINE_VERSION" {}
variable "EC_NODE_TYPE" {}
variable "EC_NODE_COUNT" {}
variable "EC_FAMILY" {}
variable "ENV" {}
variable "COMPONENT" {}
variable "VPC_ID" {}
variable "VPC_CIDR" {}
variable "SUBNET_IDS" {}